spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.jpa.open-in-view=false
spring.profiles.active=prod
fx.batch.full-load-on-startup=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/openapi.yaml